-- MySQL Script generated by MySQL Workbench
-- ter 24 mar 2020 23:37:04 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema interview
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema interview
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `interview` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `interview` ;

-- -----------------------------------------------------
-- Table `interview`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_2vf89ija5fea0souakqh3bg59` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `UK_r1u8010d60num5vc8fp0q1j2a` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `interview`.`filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`filial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `interview`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_de_barras` VARCHAR(255) NULL DEFAULT NULL,
  `custo` DOUBLE NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `sequencial` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_s8dbelljfeexcayiqfg1wihb2` (`codigo_de_barras` ASC) VISIBLE,
  UNIQUE INDEX `UK_ambefc98gg3am161v3ht85r4q` (`sequencial` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `interview`.`filial_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`filial_produto` (
  `quantidade_estoque` INT NULL DEFAULT NULL,
  `filial_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`filial_id`, `produto_id`),
  INDEX `FKjrlnra3q0xvc1k4g0jdb6doln` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `FKhybff9uux4tra6lae5y1f7b16`
    FOREIGN KEY (`filial_id`)
    REFERENCES `interview`.`filial` (`id`),
  CONSTRAINT `FKjrlnra3q0xvc1k4g0jdb6doln`
    FOREIGN KEY (`produto_id`)
    REFERENCES `interview`.`produto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `interview`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ativo` BIT(1) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `foto_url` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_5171l57faosmj8myawaucatdw` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `interview`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`pagamento` (
  `dtype` VARCHAR(31) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `custo` DOUBLE NOT NULL,
  `data_emissao` VARCHAR(255) NULL DEFAULT NULL,
  `data_vencimento` VARCHAR(255) NULL DEFAULT NULL,
  `numero_de_parcelas` INT NULL DEFAULT NULL,
  `numero_do_cartao` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `interview`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `custo_total` DOUBLE NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` INT NULL DEFAULT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  `filial_id` INT NULL DEFAULT NULL,
  `pagamento_id` INT NULL DEFAULT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK30s8j2ktpay6of18lbyqn3632` (`cliente_id` ASC) VISIBLE,
  INDEX `FKl1n770t6l2ps1k1ctqg9xcq56` (`filial_id` ASC) VISIBLE,
  INDEX `FKd8wwc5gy5hnijj7iki22jeorn` (`pagamento_id` ASC) VISIBLE,
  INDEX `FK6uxomgomm93vg965o8brugt00` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `FK30s8j2ktpay6of18lbyqn3632`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `interview`.`cliente` (`id`),
  CONSTRAINT `FK6uxomgomm93vg965o8brugt00`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `interview`.`usuario` (`id`),
  CONSTRAINT `FKd8wwc5gy5hnijj7iki22jeorn`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `interview`.`pagamento` (`id`),
  CONSTRAINT `FKl1n770t6l2ps1k1ctqg9xcq56`
    FOREIGN KEY (`filial_id`)
    REFERENCES `interview`.`filial` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `interview`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interview`.`item_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `custo_unitario` DOUBLE NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `sub_total` DOUBLE NULL DEFAULT NULL,
  `pedido_id` INT NULL,
  `produto_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK60ym08cfoysa17wrn1swyiuda` (`pedido_id` ASC) VISIBLE,
  INDEX `FKtk55mn6d6bvl5h0no5uagi3sf` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `FK60ym08cfoysa17wrn1swyiuda`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `interview`.`pedido` (`id`),
  CONSTRAINT `FKtk55mn6d6bvl5h0no5uagi3sf`
    FOREIGN KEY (`produto_id`)
    REFERENCES `interview`.`produto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
