CREATE SEQUENCE ES01_ESTOQUE_SEQ START 1;
CREATE TABLE public.ES01_ESTOQUE(
    ES01_COD_ESTOQUE BIGINT NOT NULL DEFAULT  nextval('public.ES01_ESTOQUE_SEQ'::regclass),
    FKES01ES10_COD_FILIAL BIGINT NOT NULL ,
    FKES01ES04_COD_PRODUTO BIGINT NOT NULL ,
    ES01_QTD_TOTAL INTEGER NOT NULL,
    constraint PK_ES01_ESTOQUE primary key (ES01_COD_ESTOQUE)
);

CREATE SEQUENCE ES02_PEDIDO_ESTOQUE_SEQ START  1;
CREATE TABLE public.ES02_PEDIDO_ESTOQUE(
    ES02_COD_PEDIDO_ESTOQUE BIGINT NOT NULL  DEFAULT  nextval('public.ES02_PEDIDO_ESTOQUE_SEQ'::regclass),
    FKES02ES05_COD_TIPO_PEDIDO BIGINT NOT NULL ,
    FKES02ES10_COD_FILIAL BIGINT NOT NULL ,
    FKES02ES03_COD_ITEM_PEDIDO BIGINT NOT NULL,
    ES02_OBS_ENTREGA VARCHAR(255),
    constraint PK_ES02_PEDIDO_ESTOQUE primary key (ES02_COD_PEDIDO_ESTOQUE)
);

CREATE SEQUENCE ES03_ITEM_PEDIDO_SEQ START 1;
CREATE TABLE ES03_ITEM_PEDIDO(
    ES03_COD_ITEM_PEDIDO BIGINT NOT NULL  DEFAULT nextval('public.ES02_PEDIDO_ESTOQUE_SEQ'::regclass),
    FKES03ES02_COD_PEDIDO_ESTOQUE BIGINT NOT NULL ,
    FKES03ES04_COD_PRODUTO BIGINT NOT NULL ,
    FKES03ES06_COD_STATUS BIGINT NOT NULL ,
    ES03_QUANTIDADE INTEGER NOT NULL ,
    ES03_VALOR_UNITARIO DOUBLE PRECISION,
    ES03_VALOR_TOTAL DOUBLE PRECISION,
    constraint PK_ES03_ITEM_PEDIDO primary key (ES03_COD_ITEM_PEDIDO)
);

CREATE SEQUENCE ES04_PRODUTO_SEQ START 1;
CREATE TABLE ES04_PRODUTO(
    ES04_COD_PRODUTO BIGINT NOT NULL  DEFAULT  nextval('public.ES04_PRODUTO_SEQ'::regclass),
    ES04_CDG_BARRAS VARCHAR(13),
    ES04_DESCRICAO VARCHAR(255),
    constraint PK_ES04_PRODUTO primary key (ES04_COD_PRODUTO)
);

CREATE SEQUENCE ES05_TIPO_PEDIDO_SEQ START 1;
CREATE TABLE ES05_TIPO_PEDIDO(
    ES05_COD_TIPO_PEDIDO BIGINT NOT NULL DEFAULT nextval('public.ES05_TIPO_PEDIDO_SEQ'::regclass),
    ES5_DESCRICAO VARCHAR(255),
    constraint PK_ES05_TIPO_PEDIDO primary key (ES05_COD_TIPO_PEDIDO)
);

CREATE SEQUENCE ES06_STATUS_PEDIDO_SEQ START 1;
CREATE TABLE ES06_STATUS_PEDIDO(
    ES06_COD_STATUS_PEDIDO BIGINT NOT NULL DEFAULT nextval('public.ES06_STATUS_PEDIDO_SEQ'::regclass),
    ES06_DESCRICAO VARCHAR(255),
    constraint PK_ES06_STATUS_PEDIDO primary key (ES06_COD_STATUS_PEDIDO)
);

CREATE SEQUENCE ES07_FORMA_PAG_SEQ START 1;
CREATE TABLE ES07_FORMA_PAG(
    ES07_COD_FORMA_PAG BIGINT NOT NULL DEFAULT nextval('public.ES06_FORMA_PAG_SEQ'::regclass),
    ES07_DESCRICAO VARCHAR(255),
    constraint PK_ES07_FORMA_PAG primary key (ES07_COD_FORMA_PAG)
);

CREATE SEQUENCE ES08_ENTRADA_ESTOQUE_SEQ START 1;
CREATE TABLE ES08_ENTRADA_ESTOQUE(
    ES08_COD_ENTRADA_ESTOQUE BIGINT NOT NULL DEFAULT nextval('public.ES08_ENTRADA_ESTOQUE_SEQ'::regclass),
    FKES08ES02_COD_PEDIDO_ESTOQUE BIGINT NOT NULL,
    FKES08ES11_COD_USUARIO BIGINT NOT NULL,
    constraint PK_ES08_ENTRADA_ESTOQUE primary key (ES08_COD_ENTRADA_ESTOQUE)
);

CREATE SEQUENCE ES09_COMPRA_SEQ START 1;
CREATE TABLE ES09_COMPRA(
    ES09_COD_COMPRA BIGINT NOT NULL DEFAULT nextval('public.ES09_COMPRA_SEQ'::regclass),
    FKES09ES02_COD_PEDIDO_ESTOQUE BIGINT NOT NULL,
    FKES09ES07_COD_FORMA_PAG BIGINT NOT NULL,
    FKES09ES11_COD_USUARIO BIGINT NOT NULL,
    FKES09ES12_COD_CLIENTE BIGINT NOT NULL,
    constraint PK_ES09_COMPRA primary key (ES09_COD_COMPRA)
);

CREATE SEQUENCE ES10_FILIAL_SEQ START 1;
CREATE TABLE ES10_FILIAL(
    ES10_COD_FILIAL BIGINT NOT NULL DEFAULT nextval('public.ES10_FILIAL_SEQ'::regclass),
    ES10_DESCRICAO VARCHAR (255),
    constraint PK_ES10_FILIAL primary key (ES10_COD_FILIAL)
);

CREATE SEQUENCE ES11_USUARIO_SEQ START 1;
CREATE TABLE ES11_USUARIO(
    ES11_COD_USUARIO BIGINT NOT NULL DEFAULT nextval('public.ES11_USUARIO_SEQ'::regclass),
    ES11_NOME VARCHAR (255),
    ES11_CPF VARCHAR(255),
    ES11_SENHA VARCHAR(255),
    constraint PK_ES11_USUARIO primary key (ES11_COD_USUARIO)
);

CREATE SEQUENCE ES12_CLIENTE_SEQ START 1;
CREATE TABLE public.ES12_CLIENTE(
     ES12_COD_CLIENTE BIGINT NOT NULL DEFAULT nextval('public.ES12_CLIENTE_SEQ'::regclass),
     ES12_NOME VARCHAR(255) NOT NULL ,
     ES12_CPF VARCHAR(255) NOT NULL,
     constraint PK_ES12_CLIENTE primary key (ES12_COD_CLIENTE)
);

ALTER TABLE ES01_ESTOQUE
    ADD CONSTRAINT FK_ES01_EST_REFERENCE_ES10_FIL FOREIGN KEY (FKES01ES10_COD_FILIAL)
        REFERENCES ES10_FILIAL(ES10_COD_FILIAL) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES01_ESTOQUE
    ADD CONSTRAINT FK_ES01_EST_REFERENCE_ES04_PRD FOREIGN KEY (FKES01ES04_COD_PRODUTO)
        REFERENCES ES04_PRODUTO(ES04_COD_PRODUTO) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES02_PEDIDO_ESTOQUE
    ADD CONSTRAINT FK_ES02_PED_REFERENCE_ES05_TPD FOREIGN KEY (FKES02ES05_COD_TIPO_PEDIDO)
        REFERENCES ES05_TIPO_PEDIDO(ES05_COD_TIPO_PEDIDO) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES02_PEDIDO_ESTOQUE
    ADD CONSTRAINT FK_ES02_PED_REFERENCE_ES10_FIL FOREIGN KEY (FKES02ES10_COD_FILIAL)
        REFERENCES ES10_FILIAL(ES10_COD_FILIAL) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES02_PEDIDO_ESTOQUE
    ADD CONSTRAINT FK_ES02_PED_REFERENCE_ES03_IPD FOREIGN KEY (FKES02ES03_COD_ITEM_PEDIDO)
        REFERENCES ES03_ITEM_PEDIDO(ES03_COD_ITEM_PEDIDO) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES03_ITEM_PEDIDO
    ADD CONSTRAINT FK_ES03_IPD_REFERENCE_ES02_PED FOREIGN KEY (FKES03ES02_COD_PEDIDO_ESTOQUE)
        REFERENCES ES02_PEDIDO_ESTOQUE(ES02_COD_PEDIDO_ESTOQUE) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES03_ITEM_PEDIDO
    ADD CONSTRAINT FK_ES03_IPD_REFERENCE_ES04_PRD FOREIGN KEY (FKES03ES04_COD_PRODUTO)
        REFERENCES ES04_PRODUTO(ES04_COD_PRODUTO) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES03_ITEM_PEDIDO
    ADD CONSTRAINT FK_ES03_IPD_REFERENCE_ES06_STP FOREIGN KEY (FKES03ES06_COD_STATUS)
        REFERENCES ES06_STATUS_PEDIDO(ES06_COD_STATUS_PEDIDO) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES08_ENTRADA_ESTOQUE
    ADD CONSTRAINT FK_ES08_ENT_REFERENCE_ES02_PED FOREIGN KEY (FKES08ES02_COD_PEDIDO_ESTOQUE)
        REFERENCES ES02_PEDIDO_ESTOQUE(ES02_COD_PEDIDO_ESTOQUE) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES08_ENTRADA_ESTOQUE
    ADD CONSTRAINT FK_ES08_ENT_REFERENCE_ES11_USR FOREIGN KEY (FKES08ES11_COD_USUARIO)
        REFERENCES ES11_USUARIO(ES11_COD_USUARIO) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES09_COMPRA
    ADD CONSTRAINT FK_ES09_CMP_REFERENCE_ES02_PED FOREIGN KEY (FKES09ES02_COD_PEDIDO_ESTOQUE)
        REFERENCES ES02_PEDIDO_ESTOQUE(ES02_COD_PEDIDO_ESTOQUE) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES09_COMPRA
    ADD CONSTRAINT FK_ES09_CMP_REFERENCE_ES07_FPG FOREIGN KEY (FKES09ES07_COD_FORMA_PAG)
        REFERENCES ES07_FORMA_PAG(ES07_COD_FORMA_PAG) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES09_COMPRA
    ADD CONSTRAINT FK_ES09_CMP_REFERENCE_ES11_USR FOREIGN KEY (FKES09ES11_COD_USUARIO)
        REFERENCES ES11_USUARIO(ES11_COD_USUARIO) ON DELETE RESTRICT ON UPDATE RESTRICT ;

ALTER TABLE ES09_COMPRA
    ADD CONSTRAINT FK_ES09_CMP_REFERENCE_ES12_CLI FOREIGN KEY (FKES09ES12_COD_CLIENTE)
        REFERENCES ES12_CLIENTE(ES12_COD_CLIENTE) ON DELETE RESTRICT ON UPDATE RESTRICT ;





