INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Alemanha');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Cidade Operária');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Cohab');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Forquilha');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Jaracaty');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix João Paulo');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Maracanã');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Renascença');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Tirirical');
INSERT INTO public.ES10_FILIAL (ES10_DESCRICAO) VALUES ('Mix Turu');

ALTER SEQUENCE public.ES10_FILIAL_SEQ RESTART WITH 69;