INSERT INTO public.ES05_TIPO_PEDIDO (ES05_DESCRICAO) VALUES ('Entrada');
INSERT INTO public.ES05_TIPO_PEDIDO (ES05_DESCRICAO) VALUES ('Saída');

ALTER SEQUENCE public.ES05_TIPO_PEDIDO_SEQ RESTART WITH 3;