INSERT INTO public.ES07_FORMA_PAG (ES07_DESCRICAO) VALUES ('À Vista');
INSERT INTO public.ES07_FORMA_PAG (ES07_DESCRICAO) VALUES ('Boleto');
INSERT INTO public.ES07_FORMA_PAG (ES07_DESCRICAO) VALUES ('Cartão');

ALTER SEQUENCE public.ES07_FORMA_PAG_SEQ RESTART WITH 4;